services:
  database:
    image: mysql:8
    container_name: my_database5
    environment:
      MYSQL_ROOT_PASSWORD: root # Senha do usuário root
      MYSQL_DATABASE: blog # Nome do banco de dados inicial
      MYSQL_USER: unicesumar # Nome do usuário do banco de dados
      MYSQL_PASSWORD: unicesumar # Senha do usuário do banco de dados
    ports:
      - "3336:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: my_adminer3
    environment:
      ADMINER_DEFAULT_SERVER: 
    ports:
      - "8092:8080"

volumes:
  mysql_data: